repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
        files: ^(?:\.\/)?(?:workflows\/|\.github\/workflows\/).*\.ya?ml$
      - id: check-github-actions
  - repo: https://github.com/tatari-tv/pre-commit-hooks
    rev: v0.4.0
    hooks:
      - id: gitleaks
