name: Tatari Org Lint

on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.11'

jobs:
  required-workflows-lint:
    name: Required Workflows Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: tatari-tv/github-actions/checkout@v5
      - name: create requirements-lint.txt
        shell: bash
        run: |
          cat > requirements-lint.txt <<EOF
          pre-commit~=3.1.1
          EOF
      - uses: tatari-tv/github-actions/pip-install@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache-pre-commit: 'true'
          pypi-username: ${{secrets.CI_USER_PYPI_USERNAME}}
          pypi-password: ${{secrets.CI_USER_PYPI_PASSWORD}}
          requirements: requirements-lint.txt
      - name: create .pre-commit-config.yaml
        shell: bash
        env:
          REPO: ${{github.event.pull_request.head.repo.full_name}}
        run: |
          # create list of excluded patterns based on repo
          case $REPO in
            "tatari-tv/philo-fe")
              exclude_whitespace="
                      .*\.snap|
                      .*/graphql_types/.*\.ts|
                      common/graphql/possibleTypes\.json"
              exclude_size=""
              ;;
            "tatari-tv/philo")
              exclude_whitespace=""
              exclude_size="
                      philo/util/trial_accounts/data/.*\.csv"
              ;;
            "tatari-tv/grey-matter")
              exclude_whitespace="
                      notebook/.*/.*\.py|
                      .*\.ipynb"
              exclude_size=""
              ;;
            *)
              exclude_whitespace=""
              exclude_size=""
              ;;
          esac

          cat > .pre-commit-config.yaml <<EOF
          repos:
            - repo: https://github.com/pre-commit/pre-commit-hooks
              rev: v4.1.0
              hooks:
                - id: trailing-whitespace
                  exclude: |
                    (?x)^(${exclude_whitespace}
                    )$
                - id: end-of-file-fixer
                  exclude: |
                    (?x)^(${exclude_whitespace}
                    )$
                - id: check-added-large-files
                  exclude: |
                    (?x)^(${exclude_size}
                    )$
          EOF

          echo ".pre-commit-config.yaml contents:"
          cat .pre-commit-config.yaml
      - name: run pre-commit
        shell: bash
        run: pre-commit run --all-files
