name: Tatari Org Security

on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

permissions:
  contents: read
  pull-requests: read

jobs:
  required-workflows-security:
    name: Required Workflows Security
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Initial commit')"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 1
      - name: Deepen checkout for gitleaks scan
        if: github.event_name == 'pull_request'
        env:
          COMMITS: ${{ github.event.pull_request.commits }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: git fetch --depth=$(( COMMITS + 1 )) origin pull/$PR_NUMBER/head
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e  # v3.0.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITLEAKS_LICENSE: ${{secrets.GITLEAKS_LICENSE}}
